export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const CHENGED_CATEGORY = "CHENGED_CATEGORY";
export const GET_PRODUCTS_BY_SEARCH = "GET_PRODUCTS_BY_SEARCH";
export const PAGINATION = "PAGINATION";
export const CHANGED_SIZE_PAGE = "CHANGED_SIZE_PAGE";
export const GET_PRODUCTS_BY_PRICE = "GET_PRODUCTS_BY_PRICE";
export const INITIAL_STATE = 'INITIAL_STATE';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';